kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: test
  commands:
  - coverage run -m pytest -q
  - coverage xml
- name: bandit
  commands:
  - bandit -ll -r selfprivacy_api
- name: formatting
  commands:
  - black --check .
