kind: pipeline
type: exec
name: default

steps:
- name: Run Tests and Generate Coverage Report
  commands:
  - VM_TEST_OUT_PATH="$(nix build .#checks.x86_64-linux.default --no-link --print-out-paths --print-build-logs)"
  - sonar-scanner -Dsonar.projectKey=SelfPrivacy-REST-API -Dsonar.sources="$PWD" -Dsonar.host.url=http://analyzer.lan:9000 -Dsonar.login="$SONARQUBE_TOKEN" -Dsonar.python.coverage.reportPaths="$VM_TEST_OUT_PATH/coverage.xml" -Dsonar.python.version=3.10
  environment:
    SONARQUBE_TOKEN:
      from_secret: SONARQUBE_TOKEN


- name: Run Bandit Checks
  commands:
  - bandit -ll -r selfprivacy_api

- name: Run Code Formatting Checks
  commands:
  - black --check .

node:
  server: builder

trigger:
  event:
    - push
